//  Copyright (c) Meta Platforms, Inc. and affiliates.
//  This source code is licensed under both the GPLv2 (found in the
//  COPYING file in the root directory) and Apache 2.0 License
//  (found in the LICENSE.Apache file in the root directory).
//
//  *****************************************************************
//  EXPERIMENTAL - subject to change while under development
//  *****************************************************************

#pragma once

#include <memory>
#include <string>

#include "rocksdb/advanced_iterator.h"
#include "rocksdb/customizable.h"
#include "rocksdb/options.h"
#include "rocksdb/slice.h"
#include "rocksdb/status.h"
#include "table/block_based/block_builder.h"

namespace ROCKSDB_NAMESPACE {

// Forward declarations
struct BlockContents;
class DataBlockIter;
class Statistics;

// Prefix for user-defined block names
inline const std::string kUserDefinedBlockPrefix =
    "rocksdb.user_defined_block.";

// This is a public API for user-defined block builders and block formats.
// It allows users to define their own block format and build custom
// blocks during table building. Currently, only a monolithic block
// is supported (no partitioned block).
//
// This is currently supported only for a restricted set of use cases. The
// CF must be ingest only, and only files containing Puts generated by
// SstFileWriter are supported.

// Options for user defined block
struct UserDefinedBlockOption {
  const Comparator* comparator = BytewiseComparator();
};

// ============================================================================
// User-Defined Block Interface
// ============================================================================
//
// Abstract base class for user-defined block implementations.
// Users can implement their own block formats (e.g., columnar, compressed,
// encrypted) by inheriting from this class.
//
// Example: A columnar PAX-format block would parse BlockContents into
// column-oriented storage and provide efficient column access through
// iterators.
//
class UserDefinedBlock {
 public:
  virtual ~UserDefinedBlock() = default;

  virtual Status InitBlock(BlockContents* contents) = 0;

  // Returns the approximate memory usage of this block, including any
  // auxiliary data structures (indexes, caches, etc.).
  // This is used for cache accounting and memory budgeting.
  virtual size_t ApproximateMemoryUsage() const = 0;

  // Returns a Slice pointing to the raw block contents.
  // This is used for cache key generation and content verification.
  // The returned Slice must remain valid for the lifetime of this object.
  virtual const Slice& ContentSlice() const = 0;

  // Returns the size of the block content in bytes.
  virtual size_t size() const = 0;

  // Returns a pointer to the raw block data.
  // This may be needed for compatibility with legacy code paths.
  virtual const char* data() const = 0;

  // Returns true if this block owns the underlying memory.
  // If false, the memory is owned externally (e.g., mmap'd file).
  virtual bool own_bytes() const = 0;

  // Creates a new iterator for this block.
  // The caller takes ownership of the returned iterator.
  //
  // Parameters:
  //   raw_ucmp - User comparator (not wrapped)
  //   global_seqno - Global sequence number to apply, or
  //                  kDisableGlobalSequenceNumber if disabled
  //   input_iter - If not nullptr, reuse this iterator object instead of
  //                allocating a new one
  //   stats - Statistics object for recording metrics (may be nullptr)
  //   block_contents_pinned - If true, the block data will remain valid
  //                           even after the iterator is passed to other
  //                           objects (e.g., PinnableSlice)
  //   user_defined_timestamps_persisted - Whether user-defined timestamps
  //                                       are persisted in the block
  //
  // Returns: A pointer to the iterator. If input_iter was provided and
  //          successfully reused, returns input_iter; otherwise returns
  //          a newly allocated iterator.
  virtual DataBlockIter* NewDataIterator(
      const Comparator* raw_ucmp, SequenceNumber global_seqno,
      DataBlockIter* input_iter = nullptr, Statistics* stats = nullptr,
      bool block_contents_pinned = false,
      bool user_defined_timestamps_persisted = true,
      void* user_defined_block_iterator_arg = nullptr) = 0;
};

// ============================================================================
// User-Defined Block Factory Interface
// ============================================================================
//
// Factory for creating user-defined block builders and block instances.
// Users implement this interface to plug their custom block format into
// RocksDB.
//
// The factory is responsible for:
// 1. Creating block builders for writing (NewBuilder)
// 2. Creating block iterators for reading (NewIterator) - legacy API
// 3. Creating block instances from raw bytes (NewBlock) - new API
//
class UserDefinedBlockFactory : public Customizable {
 public:
  virtual ~UserDefinedBlockFactory() = default;

  static const char* Type() { return "UserDefinedBlockFactory"; }

  static Status CreateFromString(
      const ConfigOptions& config_options, const std::string& value,
      std::shared_ptr<UserDefinedBlockFactory>* factory);

  // -------------------------------------------------------------------------
  // WRITE PATH: Creating block builders
  // -------------------------------------------------------------------------

  // Creates a new block builder for writing data.
  // The builder is used during table building to incrementally add key-value
  // pairs and produce a serialized block.
  //
  // Parameters:
  //   option - Configuration options including comparator
  //   builder - Output parameter to receive the created builder
  //
  // Returns: OK on success, or an error status
  virtual Status NewBuilder(const UserDefinedBlockOption& /*option*/,
                            std::unique_ptr<BlockBuilder>& builder) const = 0;

  // -------------------------------------------------------------------------
  // READ PATH: Creating block iterators (LEGACY API)
  // -------------------------------------------------------------------------

  // Creates a new iterator for reading a user-defined block.
  // This is the legacy API that will be called by older code paths.
  //
  // TODO: Migrate to using NewBlock() + UserDefinedBlock::NewDataIterator()
  //
  // Parameters:
  //   option - Configuration options including comparator
  //   biter - Output parameter to receive the created iterator
  //
  // Returns: OK on success, or an error status
  virtual Status NewIterator(const UserDefinedBlockOption& option,
                             DataBlockIter** biter) const = 0;

  // -------------------------------------------------------------------------
  // READ PATH: Creating block instances from raw bytes (NEW API)
  // -------------------------------------------------------------------------

  // Creates a new block instance from raw BlockContents.
  // This is the primary API for custom block formats.
  //
  // The implementation should:
  // 1. Parse the BlockContents according to the custom format
  // 2. Create internal data structures (indexes, column metadata, etc.)
  // 3. Return a UserDefinedBlock that can create iterators on demand
  //
  // BlockContents is format-agnostic - it's just raw bytes. The user's
  // implementation determines how to interpret these bytes.
  //
  // Parameters:
  //   option - Configuration options including comparator
  //   contents - Raw block bytes (ownership transferred via move)
  //   block - Output parameter to receive the created block
  //
  // Returns: OK on success, NotSupported if custom blocks aren't implemented,
  //          or another error status on failure
  //
  // Example implementation for a columnar format:
  //
  //   Status NewBlock(const UserDefinedBlockOption& option,
  //                   BlockContents&& contents,
  //                   std::unique_ptr<UserDefinedBlock>* block) const {
  //     auto pax_block = std::make_unique<PAXBlock>(
  //         std::move(contents), option.comparator);
  //     Status s = pax_block->Parse();  // Parse columnar layout
  //     if (s.ok()) {
  //       *block = std::move(pax_block);
  //     }
  //     return s;
  //   }
  //
  virtual Status NewBlock(const UserDefinedBlockOption& /*option*/,
                          std::unique_ptr<UserDefinedBlock>* /*block*/) const {
    // Default implementation: not supported
    // Users who want custom block formats must override this method
    return Status::NotSupported(
        "Custom block format not implemented by this factory");
  }

  // -------------------------------------------------------------------------
  // CAPABILITY DETECTION
  // -------------------------------------------------------------------------

  // Returns true if this factory implements custom block formats via
  // NewBlock(). When true, RocksDB will use NewBlock() to create blocks instead
  // of the standard Block class.
  //
  // Override this to return true if you implement NewBlock().
  virtual bool UsesCustomBlockFormat() const { return false; }
};

}  // namespace ROCKSDB_NAMESPACE
